In [8]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [10]:
a=[1,2,3.5,"qwer"]
a

[1, 2, 3.5, 'qwer']

In [11]:
np.array(a)

array(['1', '2', '3.5', 'qwer'], dtype='<U32')

In [13]:
arr=np.zeros(4)
arr

array([0., 0., 0., 0.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(1,5,2)

array([1., 5.])

In [17]:
np.random.rand(5)

array([0.98477224, 0.45946606, 0.27147359, 0.19168377, 0.96711425])

In [18]:
 np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.random.randint(1, 10, 2)

array([4, 2], dtype=int32)

In [25]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
arr[:6:2]

array([11, 13, 15])

In [41]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
slice=arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [43]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [51]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [54]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [55]:
a1-a2

array([-5, -5, -5, -5, -5])

In [56]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [57]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [58]:
a1//a2

array([0, 0, 0, 0, 0])

In [59]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [60]:
l=[10,20,30,40]
arr=np.array(l)

In [61]:
arr+10

array([20, 30, 40, 50])

In [70]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


In [67]:
a

array([[1, 2],
       [3, 4]])

In [68]:
b

array([[5, 6],
       [7, 8]])

In [69]:
a@b

array([[19, 22],
       [43, 50]])

In [71]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [75]:
a.T

array([[1, 3],
       [2, 4]])

In [76]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [77]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [81]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [87]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [5]:
name="qwer"
name

'qwer'

In [14]:
arr=np.random.randint(1,50,size=(10))

In [15]:
arr

array([30, 25,  4, 46, 34,  2, 21, 25, 44, 28], dtype=int32)

In [18]:
arr[1:10]

array([25,  4, 46, 34,  2, 21, 25, 44, 28], dtype=int32)

In [22]:
np.reshape

<function reshape at 0x0000023DF5F7CD70>

In [20]:
arr[arr>20]

array([30, 25, 46, 34, 21, 25, 44, 28], dtype=int32)

In [ ]:
import numpy as np

np.random.seed(42)
student_ids = np.arange(1, 201)
attendance = np.clip(np.random.normal(85, 10, 200), 50, 100).round(1)
study_hours = np.clip(np.random.normal(4, 2, 200), 0, 10).round(1)
assignments_completed = np.random.randint(0, 11, 200)
noise = np.random.normal(0, 8, 200)

marks = np.clip(
    40 + attendance * 0.3 + study_hours * 4 + assignments_completed * 1.5 +
    noise,
    0, 100
).round(1)