In [1]:
import numpy as np

np.random.seed(42)
student_ids = np.arange(1, 201)
attendance = np.clip(np.random.normal(85, 10, 200), 50, 100).round(1)
study_hours = np.clip(np.random.normal(4, 2, 200), 0, 10).round(1)
assignments_completed = np.random.randint(0, 11, 200)
noise = np.random.normal(0, 8, 200)

marks = np.clip(
    40 + attendance * 0.3 + study_hours * 4 + assignments_completed * 1.5 +
    noise,
    0, 100
).round(1)

In [2]:
marks.max()

np.float64(100.0)

In [3]:
marks.min()

np.float64(57.7)

In [4]:
marks.mean()

np.float64(88.6515)

In [5]:
np.median(marks)

np.float64(92.05)

In [6]:
marks.std()

np.float64(10.43572698713415)

In [7]:
marks.var()

np.float64(108.90439775)

In [8]:
student_ids[marks>90]

array([  1,   3,   4,   7,   8,   9,  10,  11,  12,  14,  16,  17,  21,
        25,  30,  32,  33,  35,  36,  40,  42,  43,  44,  49,  52,  53,
        54,  56,  57,  62,  67,  69,  71,  72,  73,  77,  83,  84,  85,
        86,  87,  88,  89,  91,  92,  93,  94,  95,  97,  99, 103, 104,
       105, 106, 107, 109, 112, 114, 115, 116, 119, 120, 121, 122, 124,
       127, 128, 129, 135, 138, 139, 142, 149, 151, 152, 155, 156, 158,
       159, 162, 163, 164, 165, 167, 168, 170, 172, 173, 175, 177, 178,
       179, 181, 186, 187, 188, 189, 190, 192, 194, 195, 196, 198, 199,
       200])

In [10]:
student_ids[marks<50]

array([], dtype=int64)

In [11]:
student_ids[attendance>90]

array([  3,   4,   7,   8,  10,  21,  32,  35,  41,  48,  54,  55,  56,
        60,  65,  66,  68,  72,  74,  76,  83,  87,  90,  92, 107, 114,
       119, 120, 121, 123, 125, 126, 136, 139, 142, 146, 149, 157, 160,
       162, 163, 165, 167, 168, 176, 178, 180, 181, 186, 192])

In [12]:
student_ids[attendance<75]

array([ 14,  15,  17,  20,  24,  27,  34,  36,  38,  39,  45,  50,  63,
        64,  75,  80,  96, 101, 111, 118, 124, 131, 133, 140, 143, 147,
       148, 159, 183, 190, 194, 200])

In [15]:
student_ids[(marks>80) &(attendance>80) ]

array([  1,   2,   3,   4,   7,   8,   9,  10,  11,  12,  13,  18,  21,
        30,  32,  33,  35,  40,  41,  42,  43,  44,  47,  48,  49,  52,
        54,  56,  62,  67,  68,  69,  71,  72,  73,  74,  76,  77,  78,
        79,  81,  83,  87,  88,  90,  91,  92,  94,  95,  97,  98,  99,
       103, 105, 106, 107, 109, 110, 112, 113, 114, 115, 116, 119, 120,
       121, 123, 129, 136, 138, 139, 142, 149, 151, 152, 154, 155, 158,
       160, 162, 163, 165, 167, 168, 169, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 186, 187, 188, 191, 192, 195, 196, 198, 199])